### ISSUE TITLE
new handler

### ISSUE THREAD

**Issue by biggosh** [andrewleech/PyWebDAV3#10]
Hi.

The code is structured to allow different storage handlers. 
There in "only" the file system handler, now. If I'd like to implement an other handler and make the server to use it, do I have only to change the line 76 of server.py? I checked the code and it is the only place where the handler is created.

Thanks in advance

**Comment by andrewleech** [comment]
Hi,
I really don't know sorry, I've never tried this. I haven't actually used this server for quite some time so not that familiar with the code any more either. All I can suggest is to try it!

**Comment by biggosh** [comment]
Ok, thanks
