### ISSUE TITLE
Latest release 0.9.9 does not work with Python3

### ISSUE THREAD

**Issue by aspotashev** [andrewleech/PyWebDAV3#13]
Latest release 0.9.9 does not work with Python3: the code uses old syntax, e.g. "except DAV_Error, (ec, dd):" in pywebdav/lib/WebDAVServer.py.

This was fixed 3 years ago in commit https://github.com/andrewleech/PyWebDAV3/commit/b4abb327a357d9a3feb373657c406233772b0590
Please make a new release compatible with Python3.

**Comment by andrewleech** [comment]
You're referring to the original pywebdav project. 
This is pywebdav3 which I started for python3 compatibility, as such you need to install it as pywebdav3: https://pypi.org/project/PyWebDAV3/

**Comment by aspotashev** [comment]
Thanks for the clarification!
