### ISSUE TITLE
Exception on LOCK

### ISSUE THREAD

**Issue by loeweh** [andrewleech/PyWebDAV3#26]
Hi Andrew,

- mountet the webdav on linux with davfs2
- tried a "touch test" on the share
- got an error

on the client:
===========
$ mkdir webdav
$ sudo mount -t davfs http://3.67.207.50:8000 webdav
$ cd webdav
$ touch test

[loewe@fedora webdav]$ touch test
touch: cannot touch 'test': Permission denied
[loewe@fedora webdav]$ sudo touch test
touch: cannot touch 'test': Input/output error
[loewe@fedora webdav]$ 

on the server:
===========
[ec2-user@ip-172-31-44-33 ~]$ davserver -H 0.0.0.0 -P 8000 -D /home/ec2-user/Pictures/ -n
2022-10-26 08:13:52,715 WARNING Authentication disabled!
Listening on 0.0.0.0 (8000)
93.216.217.130 - - [26/Oct/2022 08:25:17] "OPTIONS / HTTP/1.1" 200 -
93.216.217.130 - - [26/Oct/2022 08:25:17] "PROPFIND / HTTP/1.1" 207 -
93.216.217.130 - - [26/Oct/2022 08:25:17] "PROPFIND / HTTP/1.1" 207 -
93.216.217.130 - - [26/Oct/2022 08:25:26] "PROPFIND / HTTP/1.1" 207 -
93.216.217.130 - - [26/Oct/2022 08:26:05] "PROPFIND / HTTP/1.1" 207 -
93.216.217.130 - - [26/Oct/2022 08:31:04] "PROPFIND / HTTP/1.1" 207 -
93.216.217.130 - - [26/Oct/2022 08:31:16] "PROPFIND / HTTP/1.1" 207 -
93.216.217.130 - - [26/Oct/2022 08:31:16] "LOCK /test HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('93.216.217.130', 52540)
Traceback (most recent call last):
  File "/usr/lib64/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib64/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pywebdav/lib/locks.py", line 140, in do_LOCK
    {'Lock-Token' : '<opaquelocktoken:%s>' % token})
  File "/home/ec2-user/.local/lib/python3.7/site-packages/pywebdav/lib/WebDAVServer.py", line 64, in send_body
    self.send_response(code, message=msg)
  File "/usr/lib64/python3.7/http/server.py", line 492, in send_response
    self.send_response_only(code, message)
  File "/usr/lib64/python3.7/http/server.py", line 507, in send_response_only
    (self.protocol_version, code, message)).encode(
TypeError: %d format: a number is required, not str
----------------------------------------

Any idea.

Cheers

Heiko

**Comment by andrewleech** [comment]
Looks like a string is being passed to the python server code somewhere it's expecting a number, that stack trace should point to the right place in the code.

I'm not actively using or working on this tool, however I'm open to PR's for fixes for things like this.

**Comment by loeweh** [comment]
Thanks Andrew, will have a look :-)
    Am Mittwoch, 26. Oktober 2022 um 11:20:41 MESZ hat Andrew Leech ***@***.***> Folgendes geschrieben:  
 
 


Looks like a string is being passed to the python server code somewhere it's expecting a number, that stack trace should point to the right place in the code.

I'm not actively using or working on this tool, however I'm open to PR's for fixes for things like this.

**Comment by andrewleech** [comment]
Should be fixed with #27
