### ISSUE TITLE
Support for Python 3.11

### ISSUE THREAD

**Issue by mbehrle** [andrewleech/PyWebDAV3#33]
It would be nice to have support for Python 3.11 ASAP. AFAIS this Python version will be the standard version of the next upcoming Debian release and of course it would be desirable if [PyWebDAV3](https://github.com/andrewleech/PyWebDAV3) would continue to be part of it.

Currently some tests are failing in Debian unstable:
https://salsa.debian.org/tryton-team/pywebdav/-/jobs/3818462/raw

Thanks for your work!

**Comment by xypron** [comment]
The autopkgtest failure described above seems to be due to an incorrect Debian patch.
See https://salsa.debian.org/tryton-team/pywebdav/-/merge_requests/2.

**Comment by mbehrle** [comment]
This was merged, thanks for the patch.
